import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'IPhone',
      slug: 'IPhone',
      category: 'phone',
      image: '/images/iphone.jpg',
      price: 1100,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular phone',
      isFeatured: true,
      banner: '/images/iphone-banner.jpg',
    },
    {
      name: 'Macbook',
      slug: 'mac-book',
      category: 'laptop',
      image: '/images/mac.jpg',
      price: 2000,
      brand: 'Apple',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular laptop',
      isFeatured: true,
      banner: '/images/mac-banner.jpg',
    },
    {
      name: 'Toster',
      slug: 'toster',
      category: 'electronics',
      image: '/images/toster.jpg',
      price: 30,
      brand: 'philips',
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular toster',
    },
    {
      name: 'Soundbar',
      slug: 'soundbar',
      category: 'electronics',
      image: '/images/soundbar.jpg',
      price: 45,
      brand: 'samsung',
      rating: 4.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart soundbar',
    },
    {
      name: 'Air Purifier',
      slug: 'air-purifier',
      category: 'electronics',
      image: '/images/airp.jpg',
      price: 95,
      brand: 'philips',
      rating: 4.5,
      numReviews: 7,
      countInStock: 20,
      description: 'A air purifier',
    },
    {
      name: 'Heater',
      slug: 'heater',
      category: 'electronics',
      image: '/images/heater.jfif',
      price: 75,
      brand: 'philips',
      rating: 4.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A hot heater',
    },
  ],
};

export default data;
